version: '3.7'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres-latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'example'
      POSTGRES_DB: '12-spring-security'
    volumes:
      - 12-spring-security:/var/lib/postgresql/data
volumes:
  12-spring-security:
