version: '3.7'
services:
  mysqldb:
    image: 'mysql:latest'
    container_name: 'mysql-latest'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: '12-spring-security'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 12-spring-security:/var/lib/mysql
volumes:
  12-spring-security:
