spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  datasource:
    initialization-mode: always
    url: 'jdbc:mysql://localhost:3306/12-spring-security?useSSL=false'
    username: 'root'
    password: ''
logging:
  level:
    org.hibernate.dialect.function.TemplateRenderer: error
